FROM python:3.11-slim AS build
WORKDIR /src
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
COPY tests/ .

FROM python:3.11-slim
WORKDIR /src
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build /src .
CMD ["python", "-m", "pytest", "-v"]
